env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  main: ./cmd/main.go
  ldflags:
  - -s -w
  - -X github.com/sandromello/wgadmin/pkg/version.version={{ .Version }}
  - -X github.com/sandromello/wgadmin/pkg/version.gitCommit={{ .Commit }}
  - -X github.com/sandromello/wgadmin/pkg/version.buildDate={{ .Date }}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
